on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build and Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: | # TODO: win32.dev.7z should be kept somewhere else 
          sudo apt-get install mingw-w64 mercurial p7zip-full
          hg clone https://keep.imfreedom.org/pidgin/pidgin/ pidgin-2.x.y
          wget https://eion.robbmob.com/win32-dev.7z 
      - name: Setup pidgin dependencies
        run: |
          cd pidgin-2.x.y && git checkout release-2.x.y
          7z x win32-dev.7z -owin32-dev
          rm -rf win32-dev.7z
      - name: Create Build
        run: |
          make install
          make installer
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false